### ISSUE TITLE
ClassNotFoundException:processing.xml.XMLElement

### ISSUE THREAD

**Issue by dlevine90** [RandomEtc/processing-gpx#2]
When I try to run the code I get this error message highlighted over the
gpx = new GPX(this);

I've copied and pasted everything so I haven't typed anything wrong. Is this a bug or am I missing something?

**Comment by RandomEtc** [comment]
I think the new version of Processing uses a different method for XML parsing. Let me look into it. Feel free to hassle me in a day or two if I don't get back to you sooner.

**Comment by RandomEtc** [comment]
Try now?

**Comment by dlevine90** [comment]
It works now, thanks!
